#!/bin/bash

# generated by chat-gpt, should disable all devices that may wake up the PC from
# sleep, except for the ones in KEEP 

WAKEUP=/proc/acpi/wakeup
# Devices, that may interrupt sleep
# KEEP=("XHC0" "XHC2" "XH00")
KEEP=()

echo "➡️  Disabling all ACPI wakeup devices except: ${KEEP[*]}"
echo

while read -r dev; do
  if [[ " ${KEEP[*]} " =~ " $dev " ]]; then
    echo "✅ Keeping enabled: $dev"
  else
    echo "❌ Disabling: $dev"
    echo "$dev" | sudo tee $WAKEUP > /dev/null
  fi
done < <(grep '\*enabled' $WAKEUP | awk '{print $1}' | uniq)
